version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    command: mysqld --default-authentication-plugin=mysql_native_password --sql_mode=""
    restart: always
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: qwe1212!Q
      MYSQL_DATABASE: compute
    volumes:
      - ./opt/mysql/conf:/etc/mysql/conf.d:Z
      - ./opt/mysql/data:/var/lib/mysql:Z
    network_mode: host
